"""foundation: users, settings, doc_counter, audit_log

Revision ID: 0001_foundation
Revises:
Create Date: 2026-10-08 02:49:06.441733

Tables autogenerated, then hand-reviewed. Functions, triggers and grants written by hand:

  set_updated_at()         BEFORE UPDATE on every table: updated_at = now(), and
                           created_at / created_by can't be changed.
  audit_row(redact...)     AFTER INSERT/UPDATE/DELETE on audited tables: one audit_log row,
                           actor from shop.user_id. SECURITY DEFINER (owned by the schema
                           owner), because the app role may only SELECT audit_log.
  audit_log_append_only()  refuses UPDATE, DELETE and TRUNCATE on audit_log, whoever asks.

Downgrade drops everything this created, audit history included. It's the first
migration, so that's only ever run against a dev or test database.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from sqlhelpers import attach_audit, attach_updated_at, grant_app

SET_UPDATED_AT = """
CREATE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    NEW.created_at := OLD.created_at;
    NEW.created_by := OLD.created_by;
    RETURN NEW;
END $$
"""

AUDIT_ROW = """
CREATE FUNCTION audit_row() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE
    redact text[] := COALESCE(TG_ARGV::text[], '{}');
    old_row jsonb;
    new_row jsonb;
    old_j jsonb;
    new_j jsonb;
    col text;
BEGIN
    IF TG_OP <> 'INSERT' THEN old_row := to_jsonb(OLD); END IF;
    IF TG_OP <> 'DELETE' THEN new_row := to_jsonb(NEW); END IF;
    IF TG_OP = 'UPDATE' AND old_row = new_row THEN
        RETURN NULL;
    END IF;
    old_j := old_row - redact;
    new_j := new_row - redact;
    IF TG_OP = 'UPDATE' THEN
        FOREACH col IN ARRAY redact LOOP
            IF (old_row -> col) IS DISTINCT FROM (new_row -> col) THEN
                new_j := new_j || jsonb_build_object(col, '[changed]');
            END IF;
        END LOOP;
    END IF;
    INSERT INTO audit_log (user_id, table_name, row_id, action, before, after)
    VALUES (NULLIF(current_setting('shop.user_id', true), '')::integer,
            TG_TABLE_NAME, COALESCE(new_row ->> 'id', old_row ->> 'id'),
            left(TG_OP, 1), old_j, new_j);
    RETURN NULL;
END $$
"""

AUDIT_LOG_APPEND_ONLY = """
CREATE FUNCTION audit_log_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_log is append-only: % refused', TG_OP
        USING ERRCODE = 'insufficient_privilege';
END $$
"""

STANDARD_TABLES = ("app_user", "shop_setting", "doc_counter")

# revision identifiers, used by Alembic.
revision = '0001_foundation'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute(SET_UPDATED_AT)
    op.execute(AUDIT_ROW)
    op.execute(AUDIT_LOG_APPEND_ONLY)
    # Nobody but the owner calls trigger functions directly.
    for fn in ("set_updated_at()", "audit_row()", "audit_log_append_only()"):
        op.execute(f"REVOKE ALL ON FUNCTION {fn} FROM PUBLIC")

    op.create_table('app_user',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_last_step', sa.BigInteger(), nullable=True),
    sa.Column('is_partner', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('split_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("role IN ('owner', 'tech', 'viewer')", name=op.f('ck_app_user_role')),
    sa.CheckConstraint("username ~ '^[a-z0-9][a-z0-9._-]{1,63}$'", name=op.f('ck_app_user_username_format')),
    sa.CheckConstraint('session_version >= 1', name=op.f('ck_app_user_session_version_positive')),
    sa.CheckConstraint('split_pct >= 0 AND split_pct <= 100', name=op.f('ck_app_user_split_pct_range')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_app_user_created_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('username', name=op.f('uq_app_user_username'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('txid', sa.BigInteger(), server_default=sa.text('txid_current()'), nullable=False),
    sa.Column('table_name', sa.String(length=63), nullable=False),
    sa.Column('row_id', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=1), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("action IN ('I', 'U', 'D')", name=op.f('ck_audit_log_action')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_at', 'audit_log', ['at'], unique=False)
    op.create_index('ix_audit_log_table_row', 'audit_log', ['table_name', 'row_id'], unique=False)
    op.create_table('doc_counter',
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('last', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("kind IN ('EST', 'WO', 'INV', 'CM', 'PO')", name=op.f('ck_doc_counter_kind')),
    sa.CheckConstraint('last >= 0', name=op.f('ck_doc_counter_last_nonnegative')),
    sa.CheckConstraint('year BETWEEN 2000 AND 2999', name=op.f('ck_doc_counter_year_range')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_doc_counter_created_by_app_user')),
    sa.PrimaryKeyConstraint('kind', 'year', name=op.f('pk_doc_counter'))
    )
    op.create_table('shop_setting',
    sa.Column('id', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('business_name', sa.String(length=120), server_default=sa.text("'ArcadeTech Tracker'"), nullable=False),
    sa.Column('legal_name', sa.String(length=160), nullable=True),
    sa.Column('address_line1', sa.String(length=160), nullable=True),
    sa.Column('address_line2', sa.String(length=160), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('region', sa.String(length=40), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('doc_accent_color', sa.String(length=7), server_default=sa.text("'#b0126f'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("doc_accent_color ~ '^#[0-9a-fA-F]{6}$'", name=op.f('ck_shop_setting_accent_hex')),
    sa.CheckConstraint('id', name=op.f('ck_shop_setting_single_row')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_shop_setting_created_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_setting'))
    )

    for table in STANDARD_TABLES:
        attach_updated_at(table)
    attach_audit("app_user", redact=("password_hash", "totp_secret"))
    attach_audit("shop_setting")
    op.execute(
        "CREATE TRIGGER audit_log_no_update_delete BEFORE UPDATE OR DELETE ON audit_log "
        "FOR EACH ROW EXECUTE FUNCTION audit_log_append_only()"
    )
    op.execute(
        "CREATE TRIGGER audit_log_no_truncate BEFORE TRUNCATE ON audit_log "
        "FOR EACH STATEMENT EXECUTE FUNCTION audit_log_append_only()"
    )

    # Users are deactivated, never deleted; the settings row is seeded, never inserted
    # by the app; counters are never deleted; the log is written only by audit_row().
    grant_app("app_user", ["SELECT", "INSERT", "UPDATE"])
    grant_app("shop_setting", ["SELECT", "UPDATE"])
    grant_app("doc_counter", ["SELECT", "INSERT", "UPDATE"])
    grant_app("audit_log", ["SELECT"])
    # pg_dump runs as the app role (scripts/backup.sh) and must read every table.
    grant_app("alembic_version", ["SELECT"])


def downgrade():
    op.drop_table('shop_setting')
    op.drop_table('doc_counter')
    op.drop_index('ix_audit_log_table_row', table_name='audit_log')
    op.drop_index('ix_audit_log_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_user')
    op.execute("DROP FUNCTION audit_log_append_only()")
    op.execute("DROP FUNCTION audit_row()")
    op.execute("DROP FUNCTION set_updated_at()")
    op.execute("REVOKE ALL ON alembic_version FROM shop_app")
