"""customers, contacts, sites, comm log, assets, asset events

Revision ID: 0003_customers_assets
Revises: 0002_seed_settings
Create Date: 2026-10-08 06:26:39.590698

Tables autogenerated, then hand-reviewed. Written by hand:

  asset_tag_seq           numbers for asset tags (s-0042-…). A sequence is right here:
                          gaps are harmless, and a number is never handed out twice.
  asset_tag_immutable()   refuses any change to asset.tag: printed labels stay valid.
  asset_no_cycle()        refuses a parent_asset_id that would put an asset inside itself.
  updated_at triggers on every table; audit on customer, contact, site, asset.
  grants: no DELETE anywhere (rows are deactivated); comm_log and asset_event are
  append-only (INSERT, SELECT).

Downgrade drops all of it, data included.
"""
from alembic import op
import sqlalchemy as sa

from sqlhelpers import attach_audit, attach_updated_at, grant_app, grant_app_sequence

ASSET_TAG_IMMUTABLE = """
CREATE FUNCTION asset_tag_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.tag IS DISTINCT FROM OLD.tag THEN
        RAISE EXCEPTION 'asset tags never change: % stays %', NEW.tag, OLD.tag
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END $$
"""

ASSET_NO_CYCLE = """
CREATE FUNCTION asset_no_cycle() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.parent_asset_id IS NOT NULL AND EXISTS (
        WITH RECURSIVE up (id, parent_asset_id) AS (
            SELECT id, parent_asset_id FROM asset WHERE id = NEW.parent_asset_id
            UNION
            SELECT a.id, a.parent_asset_id FROM asset a JOIN up ON a.id = up.parent_asset_id
        )
        SELECT 1 FROM up WHERE up.id = NEW.id
    ) THEN
        RAISE EXCEPTION 'asset % can''t go inside one of its own parts', NEW.tag
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END $$
"""

TABLES = ("customer", "contact", "site", "comm_log", "asset", "asset_event")


# revision identifiers, used by Alembic.
revision = '0003_customers_assets'
down_revision = '0002_seed_settings'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('customer',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('dba', sa.String(length=160), nullable=True),
    sa.Column('billing_email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('phone_digits', sa.String(length=40), sa.Computed("regexp_replace(coalesce(phone, ''), '[^0-9]', '', 'g')", persisted=True), nullable=False),
    sa.Column('payment_terms', sa.String(length=16), server_default=sa.text("'due_on_receipt'"), nullable=False),
    sa.Column('tax_exempt', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('exempt_cert_no', sa.String(length=60), nullable=True),
    sa.Column('exempt_cert_expires', sa.Date(), nullable=True),
    sa.Column('sends_1099', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('referral_source', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_shop', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.Column('address_line1', sa.String(length=160), nullable=True),
    sa.Column('address_line2', sa.String(length=160), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('region', sa.String(length=40), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.CheckConstraint("kind IN ('business', 'individual')", name=op.f('ck_customer_kind')),
    sa.CheckConstraint("payment_terms IN ('due_on_receipt', 'net_15', 'net_30')", name=op.f('ck_customer_payment_terms')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_customer_created_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer'))
    )
    op.create_index('uq_customer_is_shop', 'customer', ['is_shop'], unique=True, postgresql_where=sa.text('is_shop'))
    op.create_table('comm_log',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("kind IN ('call', 'text', 'email', 'in_person', 'note')", name=op.f('ck_comm_log_kind')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_comm_log_created_by_app_user')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_comm_log_customer_id_customer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comm_log'))
    )
    op.create_index(op.f('ix_comm_log_customer_id'), 'comm_log', ['customer_id'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('phone_digits', sa.String(length=40), sa.Computed("regexp_replace(coalesce(phone, ''), '[^0-9]', '', 'g')", persisted=True), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('is_billing', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_site', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_contact_created_by_app_user')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_contact_customer_id_customer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact')),
    sa.UniqueConstraint('id', 'customer_id', name='uq_contact_id_customer')
    )
    op.create_index(op.f('ix_contact_customer_id'), 'contact', ['customer_id'], unique=False)
    op.create_table('site',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('site_contact_id', sa.Integer(), nullable=True),
    sa.Column('access_notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.Column('address_line1', sa.String(length=160), nullable=True),
    sa.Column('address_line2', sa.String(length=160), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('region', sa.String(length=40), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_site_created_by_app_user')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_site_customer_id_customer')),
    sa.ForeignKeyConstraint(['site_contact_id', 'customer_id'], ['contact.id', 'contact.customer_id'], name='fk_site_contact_same_customer'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site')),
    sa.UniqueConstraint('id', 'customer_id', name='uq_site_id_customer')
    )
    op.create_index(op.f('ix_site_customer_id'), 'site', ['customer_id'], unique=False)
    op.create_table('asset',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('tag', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('parent_asset_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('manufacturer', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('model_key', sa.String(length=60), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('serial', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('in_shop_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shop_location', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('label_printed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("kind IN ('machine', 'board', 'monitor', 'chassis', 'psu', 'other')", name=op.f('ck_asset_kind')),
    sa.CheckConstraint("model_key ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f('ck_asset_model_key_format')),
    sa.CheckConstraint("status IN ('in_service', 'in_shop', 'awaiting_pickup', 'shipped_back', 'sold', 'scrapped')", name=op.f('ck_asset_status')),
    sa.CheckConstraint("tag ~ '^s-[0-9]{4,}(-[a-z0-9]+)+$' AND length(tag) <= 40", name=op.f('ck_asset_tag_format')),
    sa.CheckConstraint('parent_asset_id IS NULL OR parent_asset_id <> id', name=op.f('ck_asset_not_own_parent')),
    sa.CheckConstraint('year BETWEEN 1950 AND 2100', name=op.f('ck_asset_year_range')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_asset_created_by_app_user')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_asset_customer_id_customer')),
    sa.ForeignKeyConstraint(['parent_asset_id', 'customer_id'], ['asset.id', 'asset.customer_id'], name='fk_asset_parent_same_customer'),
    sa.ForeignKeyConstraint(['site_id', 'customer_id'], ['site.id', 'site.customer_id'], name='fk_asset_site_same_customer'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset')),
    sa.UniqueConstraint('id', 'customer_id', name='uq_asset_id_customer'),
    sa.UniqueConstraint('tag', name=op.f('uq_asset_tag'))
    )
    op.create_index(op.f('ix_asset_customer_id'), 'asset', ['customer_id'], unique=False)
    op.create_index(op.f('ix_asset_parent_asset_id'), 'asset', ['parent_asset_id'], unique=False)
    op.create_table('asset_event',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('from_value', sa.String(length=200), nullable=True),
    sa.Column('to_value', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("kind IN ('created', 'intake', 'returned', 'ownership_change', 'moved', 'status', 'note')", name=op.f('ck_asset_event_kind')),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f('fk_asset_event_asset_id_asset')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_asset_event_created_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_event'))
    )
    op.create_index(op.f('ix_asset_event_asset_id'), 'asset_event', ['asset_id'], unique=False)

    op.execute("CREATE SEQUENCE asset_tag_seq AS integer START 1")
    op.execute(ASSET_TAG_IMMUTABLE)
    op.execute(ASSET_NO_CYCLE)
    for fn in ("asset_tag_immutable()", "asset_no_cycle()"):
        op.execute(f"REVOKE ALL ON FUNCTION {fn} FROM PUBLIC")
    op.execute("CREATE TRIGGER asset_tag_immutable BEFORE UPDATE OF tag ON asset "
               "FOR EACH ROW EXECUTE FUNCTION asset_tag_immutable()")
    op.execute("CREATE TRIGGER asset_no_cycle BEFORE INSERT OR UPDATE OF parent_asset_id ON asset "
               "FOR EACH ROW EXECUTE FUNCTION asset_no_cycle()")

    for table in TABLES:
        attach_updated_at(table)
    for table in ("customer", "contact", "site", "asset"):
        attach_audit(table)

    for table in ("customer", "contact", "site", "asset"):
        grant_app(table, ["SELECT", "INSERT", "UPDATE"])
    for table in ("comm_log", "asset_event"):
        grant_app(table, ["SELECT", "INSERT"])
    grant_app_sequence("asset_tag_seq")


def downgrade():
    op.drop_index(op.f('ix_asset_event_asset_id'), table_name='asset_event')
    op.drop_table('asset_event')
    op.drop_index(op.f('ix_asset_parent_asset_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_customer_id'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_site_customer_id'), table_name='site')
    op.drop_table('site')
    op.drop_index(op.f('ix_contact_customer_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_comm_log_customer_id'), table_name='comm_log')
    op.drop_table('comm_log')
    op.drop_index('uq_customer_is_shop', table_name='customer', postgresql_where=sa.text('is_shop'))
    op.drop_table('customer')
    op.execute("DROP FUNCTION asset_no_cycle()")
    op.execute("DROP FUNCTION asset_tag_immutable()")
    op.execute("DROP SEQUENCE asset_tag_seq")
