"""price book, parts, stock ledger, vendors; drop asset.label_printed_at

Revision ID: 0005_pricebook_parts
Revises: 0004_seed_shop_customer
Create Date: 2026-10-08

Tables autogenerated, then hand-reviewed. Written by hand:

  stock_move_lot_guard()  BEFORE INSERT on stock_move: refuses a move that would take its
                          lot below zero. Concurrent moves on one lot are serialized with a
                          transaction-scoped advisory lock (the app role can't SELECT … FOR
                          UPDATE a table it may not UPDATE).
  CHECKs on the two new shop_setting labor columns (autogenerate skips those).
  markup_tier_no_overlap  EXCLUDE: two brackets can't cover the same cost.
  updated_at triggers and audit on all eight new tables.
  grants: no DELETE except job_template_line and markup_tier (editing aids, not records);
  stock_lot and stock_move are append-only (INSERT, SELECT).

asset.label_printed_at is dropped: no QR labels on customer machines (owner,
2026-10-08). Its values aren't kept; downgrade restores the column empty.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from sqlhelpers import attach_audit, attach_updated_at, grant_app

STOCK_MOVE_LOT_GUARD = """
CREATE FUNCTION stock_move_lot_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    remaining numeric;
BEGIN
    PERFORM pg_advisory_xact_lock(4801, NEW.lot_id);
    SELECT COALESCE(sum(qty), 0) + NEW.qty INTO remaining
      FROM stock_move WHERE lot_id = NEW.lot_id;
    IF remaining < 0 THEN
        RAISE EXCEPTION 'stock lot % would go below zero (% left after this move)',
            NEW.lot_id, remaining USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END $$
"""

TABLES = ("service", "job_template", "job_template_line", "markup_tier", "vendor", "part",
          "stock_lot", "stock_move")


# revision identifiers, used by Alembic.
revision = '0005_pricebook_parts'
down_revision = '0004_seed_shop_customer'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('job_template',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('est_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint('est_hours IS NULL OR est_hours >= 0', name=op.f('ck_job_template_est_hours_nonnegative')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_job_template_created_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_template')),
    sa.UniqueConstraint('name', name=op.f('uq_job_template_name'))
    )
    op.create_table('markup_tier',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('min_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('max_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('multiplier', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint('max_cost IS NULL OR max_cost > min_cost', name=op.f('ck_markup_tier_max_above_min')),
    sa.CheckConstraint('min_cost >= 0', name=op.f('ck_markup_tier_min_nonnegative')),
    sa.CheckConstraint('multiplier > 0', name=op.f('ck_markup_tier_multiplier_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_markup_tier_created_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_markup_tier')),
    sa.UniqueConstraint('min_cost', name=op.f('uq_markup_tier_min_cost'))
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('taxable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('warranty_days', sa.Integer(), server_default=sa.text('365'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("code ~ '^[A-Z0-9][A-Z0-9-]{0,19}$'", name=op.f('ck_service_code_format')),
    sa.CheckConstraint("kind IN ('labor', 'fee', 'trip', 'diagnostic', 'shop_supplies', 'sublet', 'discount')", name=op.f('ck_service_kind')),
    sa.CheckConstraint("unit IN ('hour', 'each', 'mile')", name=op.f('ck_service_unit')),
    sa.CheckConstraint('rate >= 0', name=op.f('ck_service_rate_nonnegative')),
    sa.CheckConstraint('warranty_days >= 0', name=op.f('ck_service_warranty_nonnegative')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_service_created_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service')),
    sa.UniqueConstraint('code', name=op.f('uq_service_code'))
    )
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('account_ref', sa.String(length=60), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('resale_cert_on_file', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_vendor_created_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor'))
    )
    op.create_table('part',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('manufacturer', sa.String(length=80), nullable=True),
    sa.Column('mpn', sa.String(length=80), nullable=True),
    sa.Column('equivalents', postgresql.ARRAY(sa.String(length=80)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('unit', sa.String(length=16), server_default=sa.text("'each'"), nullable=False),
    sa.Column('default_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('price_mode', sa.String(length=8), server_default=sa.text("'fixed'"), nullable=False),
    sa.Column('sell_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('taxable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('track_stock', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('reorder_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('preferred_vendor_id', sa.Integer(), nullable=True),
    sa.Column('bin', sa.String(length=40), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('datasheet_url', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("price_mode IN ('fixed', 'markup')", name=op.f('ck_part_price_mode')),
    sa.CheckConstraint('default_cost IS NULL OR default_cost >= 0', name=op.f('ck_part_cost_nonnegative')),
    sa.CheckConstraint('reorder_point IS NULL OR reorder_point >= 0', name=op.f('ck_part_reorder_nonnegative')),
    sa.CheckConstraint('reorder_qty IS NULL OR reorder_qty > 0', name=op.f('ck_part_reorder_qty_positive')),
    sa.CheckConstraint('sell_price IS NULL OR sell_price >= 0', name=op.f('ck_part_price_nonnegative')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_part_created_by_app_user')),
    sa.ForeignKeyConstraint(['preferred_vendor_id'], ['vendor.id'], name=op.f('fk_part_preferred_vendor_id_vendor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_part')),
    sa.UniqueConstraint('sku', name=op.f('uq_part_sku'))
    )
    op.create_table('job_template_line',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint('(service_id IS NULL) <> (part_id IS NULL)', name=op.f('ck_job_template_line_service_xor_part')),
    sa.CheckConstraint('qty > 0', name=op.f('ck_job_template_line_qty_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_job_template_line_created_by_app_user')),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], name=op.f('fk_job_template_line_part_id_part')),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('fk_job_template_line_service_id_service')),
    sa.ForeignKeyConstraint(['template_id'], ['job_template.id'], name=op.f('fk_job_template_line_template_id_job_template')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_template_line'))
    )
    op.create_index(op.f('ix_job_template_line_template_id'), 'job_template_line', ['template_id'], unique=False)
    op.create_table('stock_lot',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('date_code', sa.String(length=20), nullable=True),
    sa.Column('vendor_lot', sa.String(length=40), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_stock_lot_cost_nonnegative')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_stock_lot_created_by_app_user')),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], name=op.f('fk_stock_lot_part_id_part')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], name=op.f('fk_stock_lot_vendor_id_vendor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_lot')),
    sa.UniqueConstraint('id', 'part_id', name='uq_stock_lot_id_part')
    )
    op.create_index(op.f('ix_stock_lot_part_id'), 'stock_lot', ['part_id'], unique=False)
    op.create_table('stock_move',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=10), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("reason IN ('receive', 'issue', 'return', 'adjust', 'count', 'scrap', 'rma_out')", name=op.f('ck_stock_move_reason')),
    sa.CheckConstraint('qty <> 0', name=op.f('ck_stock_move_qty_nonzero')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_stock_move_created_by_app_user')),
    sa.ForeignKeyConstraint(['lot_id', 'part_id'], ['stock_lot.id', 'stock_lot.part_id'], name='fk_stock_move_lot_same_part'),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], name=op.f('fk_stock_move_part_id_part')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_move'))
    )
    op.create_index(op.f('ix_stock_move_lot_id'), 'stock_move', ['lot_id'], unique=False)
    op.create_index(op.f('ix_stock_move_part_id'), 'stock_move', ['part_id'], unique=False)
    op.drop_column('asset', 'label_printed_at')
    op.add_column('shop_setting', sa.Column('labor_increment_hours', sa.Numeric(precision=4, scale=2), server_default=sa.text('0.25'), nullable=False))
    op.add_column('shop_setting', sa.Column('labor_minimum_hours', sa.Numeric(precision=4, scale=2), server_default=sa.text('0.50'), nullable=False))
    op.create_check_constraint(op.f('ck_shop_setting_labor_increment_positive'), 'shop_setting',
                               'labor_increment_hours > 0')
    op.create_check_constraint(op.f('ck_shop_setting_labor_minimum_nonnegative'), 'shop_setting',
                               'labor_minimum_hours >= 0')

    op.execute("ALTER TABLE markup_tier ADD CONSTRAINT markup_tier_no_overlap "
               "EXCLUDE USING gist (numrange(min_cost, max_cost, '[)') WITH &&)")

    op.execute(STOCK_MOVE_LOT_GUARD)
    op.execute("REVOKE ALL ON FUNCTION stock_move_lot_guard() FROM PUBLIC")
    op.execute("CREATE TRIGGER stock_move_lot_guard BEFORE INSERT ON stock_move "
               "FOR EACH ROW EXECUTE FUNCTION stock_move_lot_guard()")

    for table in TABLES:
        attach_updated_at(table)
        attach_audit(table)
    for table in ("service", "job_template", "vendor", "part"):
        grant_app(table, ["SELECT", "INSERT", "UPDATE"])
    for table in ("job_template_line", "markup_tier"):
        grant_app(table, ["SELECT", "INSERT", "UPDATE", "DELETE"])
    for table in ("stock_lot", "stock_move"):
        grant_app(table, ["SELECT", "INSERT"])


def downgrade():
    op.drop_constraint(op.f('ck_shop_setting_labor_minimum_nonnegative'), 'shop_setting')
    op.drop_constraint(op.f('ck_shop_setting_labor_increment_positive'), 'shop_setting')
    op.drop_column('shop_setting', 'labor_minimum_hours')
    op.drop_column('shop_setting', 'labor_increment_hours')
    op.add_column('asset', sa.Column('label_printed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_stock_move_part_id'), table_name='stock_move')
    op.drop_index(op.f('ix_stock_move_lot_id'), table_name='stock_move')
    op.drop_table('stock_move')
    op.drop_index(op.f('ix_stock_lot_part_id'), table_name='stock_lot')
    op.drop_table('stock_lot')
    op.drop_index(op.f('ix_job_template_line_template_id'), table_name='job_template_line')
    op.drop_table('job_template_line')
    op.drop_table('part')
    op.drop_table('vendor')
    op.drop_table('service')
    op.drop_table('markup_tier')
    op.drop_table('job_template')
    op.execute("DROP FUNCTION stock_move_lot_guard()")
