"""work orders, jobs, lines, time, reservations, readings, attachments

Revision ID: 0007_work
Revises: 0006_seed_services
Create Date: 2026-10-08

Phase 3a. Tables autogenerated, then hand-reviewed. Written by hand:

  work_order.warranty_of_job_id -> wo_job: added after both tables exist (the two
  tables point at each other), dropped first on downgrade.
  updated_at triggers and audit on all eight new tables.
  grants, least first:
    work_order, wo_job, reservation   SELECT, INSERT, UPDATE (never deleted)
    wo_line, time_entry, attachment   + DELETE: corrected while the work is open; audited
    work_order_tech, manual_reading   SELECT, INSERT, DELETE (a reading is never edited:
                                      a wrong one is removed and taken again)

Downgrade drops these tables and stock_move.wo_job_id, and with them every work order,
job and time entry: run it only on a database whose Phase 3 data you mean to lose.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from sqlhelpers import attach_audit, attach_updated_at, grant_app

TABLES = ("work_order", "wo_job", "work_order_tech", "wo_line", "time_entry", "reservation",
          "manual_reading", "attachment")

# revision identifiers, used by Alembic.
revision = '0007_work'
down_revision = '0006_seed_services'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('work_order',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'new'"), nullable=False),
    sa.Column('priority', sa.String(length=8), server_default=sa.text("'normal'"), nullable=False),
    sa.Column('summary', sa.String(length=200), nullable=False),
    sa.Column('promised_date', sa.Date(), nullable=True),
    sa.Column('not_to_exceed', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('warranty_of_job_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("kind IN ('on_site', 'bench', 'mail_in', 'warranty', 'consult')", name=op.f('ck_work_order_kind')),
    sa.CheckConstraint("number ~ '^WO-[0-9]{4}-[0-9]{4,}$'", name=op.f('ck_work_order_number_format')),
    sa.CheckConstraint("priority IN ('low', 'normal', 'high', 'rush')", name=op.f('ck_work_order_priority')),
    sa.CheckConstraint("status IN ('new', 'scheduled', 'in_progress', 'waiting_parts', 'waiting_approval', 'ready', 'completed', 'cancelled')", name=op.f('ck_work_order_status')),
    sa.CheckConstraint('not_to_exceed IS NULL OR not_to_exceed >= 0', name=op.f('ck_work_order_nte_nonnegative')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_work_order_created_by_app_user')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_work_order_customer_id_customer')),
    sa.ForeignKeyConstraint(['site_id', 'customer_id'], ['site.id', 'site.customer_id'], name='fk_work_order_site_same_customer'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order')),
    sa.UniqueConstraint('number', name=op.f('uq_work_order_number'))
    )
    op.create_index(op.f('ix_work_order_customer_id'), 'work_order', ['customer_id'], unique=False)
    op.create_table('wo_job',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'open'"), nullable=False),
    sa.Column('complaint', sa.Text(), nullable=False),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_via', sa.String(length=10), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('accessories', postgresql.ARRAY(sa.String(length=40)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('accessories_note', sa.String(length=200), nullable=True),
    sa.Column('inbound_tracking', sa.String(length=60), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("received_via IS NULL OR received_via IN ('drop_off', 'pickup', 'mail')", name=op.f('ck_wo_job_received_via')),
    sa.CheckConstraint("status IN ('open', 'done', 'cancelled')", name=op.f('ck_wo_job_status')),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f('fk_wo_job_asset_id_asset')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_wo_job_created_by_app_user')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], name=op.f('fk_wo_job_work_order_id_work_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wo_job'))
    )
    op.create_index(op.f('ix_wo_job_asset_id'), 'wo_job', ['asset_id'], unique=False)
    op.create_index(op.f('ix_wo_job_work_order_id'), 'wo_job', ['work_order_id'], unique=False)
    op.create_table('work_order_tech',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_work_order_tech_created_by_app_user')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_work_order_tech_user_id_app_user')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], name=op.f('fk_work_order_tech_work_order_id_work_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_tech')),
    sa.UniqueConstraint('work_order_id', 'user_id', name='uq_work_order_tech')
    )
    op.create_index(op.f('ix_work_order_tech_work_order_id'), 'work_order_tech', ['work_order_id'], unique=False)
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('wo_job_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("kind IN ('photo', 'pdf', 'receipt', 'signature', 'rail_report', 'other')", name=op.f('ck_attachment_kind')),
    sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_attachment_sha256_hex')),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_attachment_size_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_attachment_created_by_app_user')),
    sa.ForeignKeyConstraint(['wo_job_id'], ['wo_job.id'], name=op.f('fk_attachment_wo_job_id_wo_job')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment'))
    )
    op.create_index(op.f('ix_attachment_sha256'), 'attachment', ['sha256'], unique=False)
    op.create_index(op.f('ix_attachment_wo_job_id'), 'attachment', ['wo_job_id'], unique=False)
    op.create_table('manual_reading',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('wo_job_id', sa.Integer(), nullable=False),
    sa.Column('test_point', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=12), nullable=False),
    sa.Column('spec_lo', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('spec_hi', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('passed', sa.Boolean(), sa.Computed('CASE WHEN spec_lo IS NULL AND spec_hi IS NULL THEN NULL ELSE (spec_lo IS NULL OR value >= spec_lo) AND (spec_hi IS NULL OR value <= spec_hi) END', persisted=True), nullable=True),
    sa.Column('phase', sa.String(length=10), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("phase IN ('as_found', 'during', 'as_left')", name=op.f('ck_manual_reading_phase')),
    sa.CheckConstraint('spec_lo IS NULL OR spec_hi IS NULL OR spec_lo <= spec_hi', name=op.f('ck_manual_reading_spec_order')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_manual_reading_created_by_app_user')),
    sa.ForeignKeyConstraint(['wo_job_id'], ['wo_job.id'], name=op.f('fk_manual_reading_wo_job_id_wo_job')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_reading'))
    )
    op.create_index(op.f('ix_manual_reading_wo_job_id'), 'manual_reading', ['wo_job_id'], unique=False)
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('wo_job_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'reserved'"), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("status IN ('reserved', 'issued', 'released')", name=op.f('ck_reservation_status')),
    sa.CheckConstraint('qty > 0', name=op.f('ck_reservation_qty_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_reservation_created_by_app_user')),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], name=op.f('fk_reservation_part_id_part')),
    sa.ForeignKeyConstraint(['wo_job_id'], ['wo_job.id'], name=op.f('fk_reservation_wo_job_id_wo_job')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation'))
    )
    op.create_index(op.f('ix_reservation_part_id'), 'reservation', ['part_id'], unique=False)
    op.create_index(op.f('ix_reservation_wo_job_id'), 'reservation', ['wo_job_id'], unique=False)
    op.create_table('time_entry',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('wo_job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('billable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("source IN ('timer', 'manual')", name=op.f('ck_time_entry_source')),
    sa.CheckConstraint('(ended_at IS NULL) = (minutes IS NULL)', name=op.f('ck_time_entry_minutes_when_ended')),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name=op.f('ck_time_entry_ends_after_start')),
    sa.CheckConstraint('minutes IS NULL OR minutes BETWEEN 0 AND 10080', name=op.f('ck_time_entry_minutes_range')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_time_entry_created_by_app_user')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_time_entry_user_id_app_user')),
    sa.ForeignKeyConstraint(['wo_job_id'], ['wo_job.id'], name=op.f('fk_time_entry_wo_job_id_wo_job')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_entry'))
    )
    op.create_index(op.f('ix_time_entry_wo_job_id'), 'time_entry', ['wo_job_id'], unique=False)
    op.create_index('uq_time_entry_one_running', 'time_entry', ['user_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    op.create_table('wo_line',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('wo_job_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('stock_lot_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('labor_mode', sa.String(length=8), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('taxable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('warranty_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('billable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('customer_supplied', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tech_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("(kind = 'labor') = (labor_mode IS NOT NULL)", name=op.f('ck_wo_line_labor_mode_iff_labor')),
    sa.CheckConstraint("NOT customer_supplied OR (kind = 'part' AND unit_price = 0 AND warranty_days = 0 AND stock_lot_id IS NULL)", name=op.f('ck_wo_line_customer_supplied_part')),
    sa.CheckConstraint("kind <> 'part' OR part_id IS NOT NULL OR customer_supplied", name=op.f('ck_wo_line_part_line_has_part')),
    sa.CheckConstraint("kind IN ('labor', 'part', 'fee', 'sublet', 'discount')", name=op.f('ck_wo_line_kind')),
    sa.CheckConstraint("labor_mode IS NULL OR labor_mode IN ('actual', 'flat')", name=op.f('ck_wo_line_labor_mode')),
    sa.CheckConstraint("qty > 0 OR (labor_mode = 'actual' AND qty >= 0)", name=op.f('ck_wo_line_qty_positive')),
    sa.CheckConstraint("stock_lot_id IS NULL OR kind = 'part'", name=op.f('ck_wo_line_lot_only_on_parts')),
    sa.CheckConstraint('unit_cost IS NULL OR unit_cost >= 0', name=op.f('ck_wo_line_cost_nonnegative')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_wo_line_price_nonnegative')),
    sa.CheckConstraint('warranty_days >= 0', name=op.f('ck_wo_line_warranty_nonnegative')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_wo_line_created_by_app_user')),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], name=op.f('fk_wo_line_part_id_part')),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('fk_wo_line_service_id_service')),
    sa.ForeignKeyConstraint(['stock_lot_id', 'part_id'], ['stock_lot.id', 'stock_lot.part_id'], name='fk_wo_line_lot_same_part'),
    sa.ForeignKeyConstraint(['tech_user_id'], ['app_user.id'], name=op.f('fk_wo_line_tech_user_id_app_user')),
    sa.ForeignKeyConstraint(['wo_job_id'], ['wo_job.id'], name=op.f('fk_wo_line_wo_job_id_wo_job')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wo_line'))
    )
    op.create_index(op.f('ix_wo_line_part_id'), 'wo_line', ['part_id'], unique=False)
    op.create_index(op.f('ix_wo_line_wo_job_id'), 'wo_line', ['wo_job_id'], unique=False)
    op.create_index('uq_wo_line_one_actual_labor', 'wo_line', ['wo_job_id'], unique=True, postgresql_where=sa.text("labor_mode = 'actual'"))
    op.add_column('shop_setting', sa.Column('claim_terms', sa.Text(), nullable=True))
    op.add_column('shop_setting', sa.Column('warranty_terms', sa.Text(), nullable=True))
    op.add_column('stock_move', sa.Column('wo_job_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stock_move_wo_job_id'), 'stock_move', ['wo_job_id'], unique=False)
    op.create_foreign_key(op.f('fk_stock_move_wo_job_id_wo_job'), 'stock_move', 'wo_job', ['wo_job_id'], ['id'])
    op.create_foreign_key('fk_work_order_warranty_of_job', 'work_order', 'wo_job',
                          ['warranty_of_job_id'], ['id'])

    for table in TABLES:
        attach_updated_at(table)
        attach_audit(table)
    for table in ("work_order", "wo_job", "reservation"):
        grant_app(table, ["SELECT", "INSERT", "UPDATE"])
    for table in ("wo_line", "time_entry", "attachment"):
        grant_app(table, ["SELECT", "INSERT", "UPDATE", "DELETE"])
    for table in ("work_order_tech", "manual_reading"):
        grant_app(table, ["SELECT", "INSERT", "DELETE"])


def downgrade():
    op.drop_constraint('fk_work_order_warranty_of_job', 'work_order', type_='foreignkey')
    op.drop_constraint(op.f('fk_stock_move_wo_job_id_wo_job'), 'stock_move', type_='foreignkey')
    op.drop_index(op.f('ix_stock_move_wo_job_id'), table_name='stock_move')
    op.drop_column('stock_move', 'wo_job_id')
    op.drop_column('shop_setting', 'warranty_terms')
    op.drop_column('shop_setting', 'claim_terms')
    op.drop_index('uq_wo_line_one_actual_labor', table_name='wo_line', postgresql_where=sa.text("labor_mode = 'actual'"))
    op.drop_index(op.f('ix_wo_line_wo_job_id'), table_name='wo_line')
    op.drop_index(op.f('ix_wo_line_part_id'), table_name='wo_line')
    op.drop_table('wo_line')
    op.drop_index('uq_time_entry_one_running', table_name='time_entry', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_index(op.f('ix_time_entry_wo_job_id'), table_name='time_entry')
    op.drop_table('time_entry')
    op.drop_index(op.f('ix_reservation_wo_job_id'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_part_id'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_manual_reading_wo_job_id'), table_name='manual_reading')
    op.drop_table('manual_reading')
    op.drop_index(op.f('ix_attachment_wo_job_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_sha256'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_index(op.f('ix_work_order_tech_work_order_id'), table_name='work_order_tech')
    op.drop_table('work_order_tech')
    op.drop_index(op.f('ix_wo_job_work_order_id'), table_name='wo_job')
    op.drop_index(op.f('ix_wo_job_asset_id'), table_name='wo_job')
    op.drop_table('wo_job')
    op.drop_index(op.f('ix_work_order_customer_id'), table_name='work_order')
    op.drop_table('work_order')
