"""estimates, customer links, appointments, calendar feeds

Revision ID: 0008_estimates
Revises: 0007_work
Create Date: 2026-10-08

Phase 3b. Tables autogenerated, then hand-reviewed. Written by hand:

  estimate_frozen()        BEFORE UPDATE OR DELETE on estimate: once approved_at is set,
                           only status (approved -> converted) and work_order_id (once)
                           may change; no delete.
  estimate_child_frozen()  BEFORE INSERT/UPDATE/DELETE on estimate_job and estimate_line:
                           refused once the estimate is approved. It takes a share lock on
                           the estimate row, so an edit and an approval can't interleave.
  CHECKs on the new columns of existing tables (autogenerate skips those).
  updated_at triggers everywhere; audit everywhere except doc_link (each view updates
  it; the token hash isn't a secret worth logging and the audit would be noise).
  grants, least first:
    estimate, doc_link, calendar_feed   SELECT, INSERT, UPDATE
    estimate_job, estimate_line         + DELETE (drafts are edited; the trigger guards)
    appointment                         + DELETE (rescheduled, cancelled)
    appointment_user                    SELECT, INSERT, DELETE

Downgrade drops these tables and columns, and with them every estimate and approval:
run it only on a database whose Phase 3b data you mean to lose.
"""
from alembic import op
import sqlalchemy as sa

from sqlhelpers import attach_audit, attach_updated_at, grant_app

ESTIMATE_FROZEN = """
CREATE FUNCTION estimate_frozen() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.approved_at IS NULL THEN
        IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'estimate % r% is approved and can''t be deleted', OLD.number,
            OLD.revision USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    IF (to_jsonb(NEW) - 'status' - 'work_order_id' - 'updated_at')
           IS DISTINCT FROM (to_jsonb(OLD) - 'status' - 'work_order_id' - 'updated_at')
       OR (NEW.status IS DISTINCT FROM OLD.status
           AND NOT (OLD.status = 'approved' AND NEW.status = 'converted'))
       OR (OLD.work_order_id IS NOT NULL
           AND NEW.work_order_id IS DISTINCT FROM OLD.work_order_id) THEN
        RAISE EXCEPTION 'estimate % r% is approved: it can''t change (make a revision)',
            OLD.number, OLD.revision USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END $$
"""

ESTIMATE_CHILD_FROZEN = """
CREATE FUNCTION estimate_child_frozen() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    approved timestamptz;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        SELECT approved_at INTO approved FROM estimate WHERE id = OLD.estimate_id FOR SHARE;
        IF approved IS NOT NULL THEN
            RAISE EXCEPTION 'estimate % is approved: its jobs and lines can''t change',
                OLD.estimate_id USING ERRCODE = 'integrity_constraint_violation';
        END IF;
    END IF;
    IF TG_OP <> 'DELETE' THEN
        SELECT approved_at INTO approved FROM estimate WHERE id = NEW.estimate_id FOR SHARE;
        IF approved IS NOT NULL THEN
            RAISE EXCEPTION 'estimate % is approved: its jobs and lines can''t change',
                NEW.estimate_id USING ERRCODE = 'integrity_constraint_violation';
        END IF;
        RETURN NEW;
    END IF;
    RETURN OLD;
END $$
"""

TABLES = ("estimate", "estimate_job", "estimate_line", "doc_link", "appointment",
          "appointment_user", "calendar_feed")


# revision identifiers, used by Alembic.
revision = '0008_estimates'
down_revision = '0007_work'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('calendar_feed',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_sha256', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("token_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_calendar_feed_token_sha256_hex')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_calendar_feed_created_by_app_user')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_calendar_feed_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_feed')),
    sa.UniqueConstraint('token_sha256', name=op.f('uq_calendar_feed_token_sha256'))
    )
    op.create_index('uq_calendar_feed_one_live', 'calendar_feed', ['user_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_appointment_ends_after_start')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_appointment_created_by_app_user')),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_appointment_site_id_site')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], name=op.f('fk_appointment_work_order_id_work_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment'))
    )
    op.create_index(op.f('ix_appointment_starts_at'), 'appointment', ['starts_at'], unique=False)
    op.create_index(op.f('ix_appointment_work_order_id'), 'appointment', ['work_order_id'], unique=False)
    op.create_table('estimate',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=12), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('not_to_exceed', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deposit_required', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('terms_snapshot', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_name', sa.String(length=120), nullable=True),
    sa.Column('approval_method', sa.String(length=10), nullable=True),
    sa.Column('approval_note', sa.String(length=300), nullable=True),
    sa.Column('approval_ip', sa.String(length=45), nullable=True),
    sa.Column('approval_ua', sa.String(length=300), nullable=True),
    sa.Column('signature_sha256', sa.String(length=64), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decline_reason', sa.String(length=300), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("approval_method <> 'link' OR (signature_sha256 IS NOT NULL AND approval_ip IS NOT NULL)", name=op.f('ck_estimate_link_approval_signed')),
    sa.CheckConstraint("approval_method IS NULL OR approval_method IN ('link', 'on_screen', 'verbal')", name=op.f('ck_estimate_approval_method')),
    sa.CheckConstraint("number ~ '^EST-[0-9]{4}-[0-9]{4,}$'", name=op.f('ck_estimate_number_format')),
    sa.CheckConstraint("signature_sha256 IS NULL OR signature_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_estimate_signature_sha256_hex')),
    sa.CheckConstraint("status IN ('draft', 'sent', 'approved', 'declined', 'superseded', 'converted')", name=op.f('ck_estimate_status')),
    sa.CheckConstraint("status NOT IN ('approved', 'converted') OR approved_at IS NOT NULL", name=op.f('ck_estimate_approved_has_approval')),
    sa.CheckConstraint('(approved_at IS NULL) = (approval_method IS NULL) AND (approved_at IS NULL) = (approved_name IS NULL)', name=op.f('ck_estimate_approval_complete')),
    sa.CheckConstraint('deposit_required IS NULL OR deposit_required >= 0', name=op.f('ck_estimate_deposit_nonnegative')),
    sa.CheckConstraint('not_to_exceed IS NULL OR not_to_exceed >= 0', name=op.f('ck_estimate_nte_nonnegative')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_estimate_revision_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_estimate_created_by_app_user')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_estimate_customer_id_customer')),
    sa.ForeignKeyConstraint(['site_id', 'customer_id'], ['site.id', 'site.customer_id'], name='fk_estimate_site_same_customer'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['estimate.id'], name=op.f('fk_estimate_supersedes_id_estimate')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], name=op.f('fk_estimate_work_order_id_work_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estimate')),
    sa.UniqueConstraint('number', 'revision', name='uq_estimate_number_revision')
    )
    op.create_index(op.f('ix_estimate_customer_id'), 'estimate', ['customer_id'], unique=False)
    op.create_index(op.f('ix_estimate_work_order_id'), 'estimate', ['work_order_id'], unique=False)
    op.create_table('appointment_user',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name=op.f('fk_appointment_user_appointment_id_appointment')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_appointment_user_created_by_app_user')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_appointment_user_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_user')),
    sa.UniqueConstraint('appointment_id', 'user_id', name='uq_appointment_user')
    )
    op.create_index(op.f('ix_appointment_user_appointment_id'), 'appointment_user', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_user_user_id'), 'appointment_user', ['user_id'], unique=False)
    op.create_table('doc_link',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('estimate_id', sa.Integer(), nullable=False),
    sa.Column('token_sha256', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("token_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_doc_link_token_sha256_hex')),
    sa.CheckConstraint('view_count >= 0', name=op.f('ck_doc_link_views_nonnegative')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_doc_link_created_by_app_user')),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimate.id'], name=op.f('fk_doc_link_estimate_id_estimate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doc_link')),
    sa.UniqueConstraint('token_sha256', name=op.f('uq_doc_link_token_sha256'))
    )
    op.create_index(op.f('ix_doc_link_estimate_id'), 'doc_link', ['estimate_id'], unique=False)
    op.create_table('estimate_job',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('estimate_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('complaint', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f('fk_estimate_job_asset_id_asset')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_estimate_job_created_by_app_user')),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimate.id'], name=op.f('fk_estimate_job_estimate_id_estimate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estimate_job')),
    sa.UniqueConstraint('id', 'estimate_id', name='uq_estimate_job_id_estimate')
    )
    op.create_index(op.f('ix_estimate_job_estimate_id'), 'estimate_job', ['estimate_id'], unique=False)
    op.create_table('estimate_line',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('estimate_id', sa.Integer(), nullable=False),
    sa.Column('estimate_job_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('labor_mode', sa.String(length=8), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('taxable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('warranty_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), server_default=sa.text("NULLIF(current_setting('shop.user_id', true), '')::integer"), nullable=True),
    sa.CheckConstraint("(kind = 'labor') = (labor_mode IS NOT NULL)", name=op.f('ck_estimate_line_labor_mode_iff_labor')),
    sa.CheckConstraint("kind <> 'part' OR part_id IS NOT NULL", name=op.f('ck_estimate_line_part_line_has_part')),
    sa.CheckConstraint("kind IN ('labor', 'part', 'fee', 'sublet', 'discount')", name=op.f('ck_estimate_line_kind')),
    sa.CheckConstraint("labor_mode IS NULL OR labor_mode IN ('actual', 'flat')", name=op.f('ck_estimate_line_labor_mode')),
    sa.CheckConstraint('qty > 0', name=op.f('ck_estimate_line_qty_positive')),
    sa.CheckConstraint('unit_cost IS NULL OR unit_cost >= 0', name=op.f('ck_estimate_line_cost_nonnegative')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_estimate_line_price_nonnegative')),
    sa.CheckConstraint('warranty_days >= 0', name=op.f('ck_estimate_line_warranty_nonnegative')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_estimate_line_created_by_app_user')),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimate.id'], name=op.f('fk_estimate_line_estimate_id_estimate')),
    sa.ForeignKeyConstraint(['estimate_job_id', 'estimate_id'], ['estimate_job.id', 'estimate_job.estimate_id'], name='fk_estimate_line_job_same_estimate'),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], name=op.f('fk_estimate_line_part_id_part')),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('fk_estimate_line_service_id_service')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estimate_line'))
    )
    op.create_index(op.f('ix_estimate_line_estimate_id'), 'estimate_line', ['estimate_id'], unique=False)
    op.create_index('ix_estimate_line_estimate_job_id', 'estimate_line', ['estimate_job_id'], unique=False)
    op.add_column('reservation', sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('shop_setting', sa.Column('estimate_terms', sa.Text(), nullable=True))
    op.add_column('shop_setting', sa.Column('estimate_link_days', sa.Integer(), server_default=sa.text('30'), nullable=False))

    op.create_check_constraint(op.f('ck_reservation_price_nonnegative'), 'reservation',
                               'unit_price IS NULL OR unit_price >= 0')
    op.create_check_constraint(op.f('ck_shop_setting_estimate_link_days_range'), 'shop_setting',
                               'estimate_link_days BETWEEN 1 AND 365')

    for sql in (ESTIMATE_FROZEN, ESTIMATE_CHILD_FROZEN):
        op.execute(sql)
    for fn in ("estimate_frozen", "estimate_child_frozen"):
        op.execute(f"REVOKE ALL ON FUNCTION {fn}() FROM PUBLIC")
    op.execute("CREATE TRIGGER estimate_frozen BEFORE UPDATE OR DELETE ON estimate "
               "FOR EACH ROW EXECUTE FUNCTION estimate_frozen()")
    for table in ("estimate_job", "estimate_line"):
        op.execute(f"CREATE TRIGGER {table}_frozen BEFORE INSERT OR UPDATE OR DELETE ON {table} "
                   "FOR EACH ROW EXECUTE FUNCTION estimate_child_frozen()")

    for table in TABLES:
        attach_updated_at(table)
        if table != "doc_link":
            attach_audit(table)
    for table in ("estimate", "doc_link", "calendar_feed"):
        grant_app(table, ["SELECT", "INSERT", "UPDATE"])
    for table in ("estimate_job", "estimate_line", "appointment"):
        grant_app(table, ["SELECT", "INSERT", "UPDATE", "DELETE"])
    grant_app("appointment_user", ["SELECT", "INSERT", "DELETE"])

def downgrade():
    op.drop_constraint(op.f('ck_shop_setting_estimate_link_days_range'), 'shop_setting')
    op.drop_constraint(op.f('ck_reservation_price_nonnegative'), 'reservation')
    op.drop_column('shop_setting', 'estimate_link_days')
    op.drop_column('shop_setting', 'estimate_terms')
    op.drop_column('reservation', 'unit_price')
    op.drop_index('ix_estimate_line_estimate_job_id', table_name='estimate_line')
    op.drop_index(op.f('ix_estimate_line_estimate_id'), table_name='estimate_line')
    op.drop_table('estimate_line')
    op.drop_index(op.f('ix_estimate_job_estimate_id'), table_name='estimate_job')
    op.drop_table('estimate_job')
    op.drop_index(op.f('ix_doc_link_estimate_id'), table_name='doc_link')
    op.drop_table('doc_link')
    op.drop_index(op.f('ix_appointment_user_user_id'), table_name='appointment_user')
    op.drop_index(op.f('ix_appointment_user_appointment_id'), table_name='appointment_user')
    op.drop_table('appointment_user')
    op.drop_index(op.f('ix_estimate_work_order_id'), table_name='estimate')
    op.drop_index(op.f('ix_estimate_customer_id'), table_name='estimate')
    op.drop_table('estimate')
    op.drop_index(op.f('ix_appointment_work_order_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_starts_at'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index('uq_calendar_feed_one_live', table_name='calendar_feed', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('calendar_feed')
    op.execute("DROP FUNCTION estimate_child_frozen()")
    op.execute("DROP FUNCTION estimate_frozen()")
